public with sharing class PORTAL_CONST_Newsletter {
    public static final String NEWSLETTER_SUBMISSION_PAGE_NAME = 'Newsletter Submission';
    public static final String MERGE_FIELDS_MAIN_SECTION = 'Listing_Merge_Fields';
    public static final String NEWSLETTER_TEMPLATE = 'Newsletter_Template';
    public static final String NEWSLETTER_CAMPAIGN = 'Newsletter_Campaign';
    public static final String NEWSLETTER_SECTION_TEMPLATE_RECORD_TYPE = 'Newsletter_Section_Template';
    public static final String MAILGUN_CONST = 'Mailgun';
}