global with sharing class PORTAL_CONST_Directory {
    global final static String SEARCH_CATEGORY_DEFAULT_SCOPE = 'Default Scope';

    global final static String NON_USER_MESSAGE_EMAIL_TEMPLATE = 'Portal_Directory_Non_User_Message_Template';
    global final static String RECEIVING_USER_FIRST_NAME = 'Receiving_User.FirstName';
    global final static String RECEIVING_USER_LAST_NAME = 'Receiving_User.LastName';
    global final static String SENDING_USER_FIRST_NAME = 'Sending_User.FirstName';
    global final static String SENDING_USER_LAST_NAME = 'Sending_User.LastName';
    global final static String MESSAGE_MERGE_FIELD_BODY = 'body';

    global final static String NUMBER_OF_CONTACTS_TO_PULL_METADATA_NAME = 'Directory_Number_of_Contacts_Pulled';

    global final static String SEARCH_DISPLAY_SETTING_CUSTOM_METADATA_TYPE = 'Portal_Directory_Search_Display_Setting__mdt';

    global final static String DUMMY_CACHE_DESC = 'Dummy_Cache_DESC';
    global final static Integer ID_LENGTH_WITH_SEMICOLON = 19;
}