public inherited sharing class PORTAL_CONST_HonorRoll {
    public static final String CONTACT_HONOR_ROLL_JOINT_PREFERENCE_INDIVIDUAL = 'Individual';
    public static final String CONTACT_HONOR_ROLL_JOINT_PREFERENCE_JOINT = 'Joint';

    public static final String GIVING_SOCIETY_TYPE_LIFETIME = 'Lifetime';

    public static final String SOCIETY_MEMBERSHIP_OBJECT_NAME = 'ucinn_ascendv2__Society_Membership__c';
}