public with sharing class PORTAL_CONST_ActionOnContent {
    public static final String USER_ID_KEY = 'userId';
    public static final String LISTING_ITEM_KEY = 'listingItem';
    public static final String LISTING_ID_KEY = 'listingId';
    public static final String USER_TYPE_KEY = 'userType';
    public static final String MAX_ITEMS_KEY = 'maxItems';
    public static final String PAGE_NAME_KEY = 'pageName';
    public static final String MAIN_SECTION_NAME_KEY = 'mainSectionName';
    public static final String SUB_SECTION_NAME_KEY = 'subSectionName';
    public static final String DYNAMIC_QUERY_OBJECT_KEY = 'dynamicQueryObject';
    public static final String PAGE_SECTION_LIST_KEY = 'pageSectionList';
    public static final String RECOMMENDATION_TYPE_LIST_KEY = 'recommendationTypeList';
    public static final String CONTENT_ID_KEY = 'contentId';
    public static final String IP_ADDRESS_KEY = 'ipAddress';
    public static final String GUEST_USER_TYPE = 'Guest';
}