public inherited sharing class PORTAL_CONST_Volunteers {
    public static final String VOLUNTEER_HOURS_OBJECT_API_NAME = 'ucinn_portal_Volunteer_Hours__c';
    public static final String VOLUNTEER_SHIFT_OBJECT_API_NAME = 'ucinn_portal_Volunteer_Shift__c';
    public static final String VOLUNTEER_JOB_OBJECT_API_NAME = 'ucinn_portal_Volunteer_Job__c';

    public static final String REMINDER_EMAIL_DATE_TIME_API_NAME = 'Reminder_Email_Date_Time__c';
    public static final String REMINDER_EMAIL_TEMPLATE_API_NAME = 'Reminder_Email_Template__c';
    public static final String IS_REMINDER_EMAIL_SENT_API_NAME = 'Is_Reminder_Email_Sent__c';

    public static final String VOLUNTEER_STATUS_COMPLETED = 'Completed';

    public static final String DEFAULT_EMAIL_SENDER_NAME = 'Volunteer Notification';
}