public with sharing class PORTAL_CONST_CommunityUser {

    public static final String WELCOME_EMAIL_SUFFIX = ' Welcome Email';
    public static final String PROFILE_SUFFIX = ' Profile';
    public static final String HIRING_MANAGER = ' Hiring Manager';
    public static final String MANUAL_REVIEW = 'Manual Review';
    public static final String COMPLETED = 'Completed';
    public static final String IN_PROGRESS = 'In Progress';
    public static final String PENDING = 'Pending';
    public static final String UNDER_APPROVAL = 'Under Approval';
    public static final String USERNAME_SUFFIX_CUSTOM_METADATA_NAME = 'Username Suffix';
    public static final String USERNAME_SUFFIX_CUSTOM_METADATA_DEVELOPER_NAME = 'Username_Suffix';
    public static final String USERNAME_PREFIX_CUSTOM_METADATA_NAME = 'Username Prefix';
    public static final String USERNAME_PREFIX_CUSTOM_METADATA_DEVELOPER_NAME = 'Username_Prefix';
    public static final String ALUMNI_PORTAL = 'Alumni Portal';
    public static final String HIRING_MANAGER_RECORDTYPE = 'Hiring_Manager_Request';
    public static final String LOGIN_REQUEST_RECORDTYPE = 'Login_Request';
    public static final String LOGIN = 'Login Request';
    public static final String DEFAULT_EMAIL_TEMPLATE = 'Alumni_Portal_Welcome_Email';
}